version: '3'

services:
  main-server:
    build: ./
    image: artofimagination/main-server
    container_name: main-server
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock